### ISSUE TITLE
打开蓝牙设置特别卡而且连不上蓝牙

### ISSUE THREAD

**Issue by wang7621422811** [SukkaW/Lenovo-Y9000X-Hackintosh#21]
<img width="309" alt="image" src="https://user-images.githubusercontent.com/52541372/186302207-76fe4a10-3089-4190-917c-1ae3ecf0d912.png">
<img width="668" alt="image" src="https://user-images.githubusercontent.com/52541372/186302260-06b68eaf-099d-4ef0-93af-6d422bf3e963.png">
<img width="260" alt="image" src="https://user-images.githubusercontent.com/52541372/186302267-d084d4a3-b7fb-45d2-ba00-3a883f106cc1.png">

**Comment by SukkaW** [comment]
```bash
sudo pkill bluetoothd && sudo launchctl start com.apple.bluetoothd
```
