### ISSUE TITLE
macOS Ventura第二次休眠无法唤醒

### ISSUE THREAD

**Issue by docee** [SukkaW/Lenovo-Y9000X-Hackintosh#29]
各位有没有升级到了macOS 13？

我先尝鲜了下，OC等都升级了。大部分功能都是正常的。**只有第二次休眠的时候无法唤醒**，目前暂时不知道是EFI的兼容问题还是macOS 系统的Bug，毕竟白果也有很多Intel机型升级后反馈无法休眠唤醒的。

**Comment by huwenfeng233** [comment]
你好，你能提供一下编译好的EFI吗，不知道为啥在我电脑上编译总是提示下载一些组件失败
