### ISSUE TITLE
Mac能用同样方法解决外放吗？

### ISSUE THREAD

**Issue by Sulisong** [SukkaW/Lenovo-Y9000X-Hackintosh#5]
原文地址
https://club.lenovo.com.cn/thread-7817162-1-1.html

解决方法
在/lib/firmware/目录下新建一个文件legion-alc285-0.0.1.patch
在/etc/modprobe.d/目录下新建文件legion-alc285-0.0.1.conf

有人在Linux系统解决了

**Comment by SukkaW** [comment]
> 或者试试ID71 ![image](https://user-images.githubusercontent.com/40148554/139426554-f4f3ebb5-2ea7-4ce3-8a46-1affa3ff9124.png)

@Sulisong ID 71 是和 Y9000X 的 codec 最接近的，但是包含有额外设备。我请 @R-a-s-c-a-l 帮忙定制了新的 layout（参见 https://github.com/acidanthera/AppleALC/pull/720）。

以及原始的 Custom Verb 太冗长了，@elmkzgirxp [精简后的 Custom Verb](https://github.com/thesofproject/linux/issues/2748) 是可用的（在 Hackintosh 和 Linux 下皆有效）

**Comment by Sulisong** [comment]
> acidanthera/AppleALC#720

很nice，期待可用

**Comment by Sulisong** [comment]
> > 或者试试ID71 ![image](https://user-images.githubusercontent.com/40148554/139426554-f4f3ebb5-2ea7-4ce3-8a46-1affa3ff9124.png)
> 
> @Sulisong ID 71 是和 Y9000X 的 codec 最接近的，但是包含有额外设备。我请 @R-a-s-c-a-l 帮忙定制了新的 layout（参见 [acidanthera/AppleALC#720](https://github.com/acidanthera/AppleALC/pull/720) ）。
> 
> 以及原始的 Custom Verb 太冗长了，@elmkzgirxp [精简后的 Custom Verb](https://github.com/thesofproject/linux/issues/2748) 是可用的（在 Hackintosh 和 Linux 下皆有效）

使用你提交的AppleALC分支，测试了并没有效果
![image](https://user-images.githubusercontent.com/40148554/140507939-86d0279d-715e-4083-9e1b-72f19a30aa6e.png)

**Comment by SukkaW** [comment]
> 使用你提交的AppleALC分支，测试了并没有效果

这个 Layout 只是添加了正确的扬声器路径；仍然需要额外配合 Custom Verb 才能为扬声器供电。

**Comment by Sulisong** [comment]
> > 使用你提交的AppleALC分支，测试了并没有效果
> 
> 这个 Layout 只是添加了正确的扬声器路径；仍然需要额外配合 [Custom Verb](https://github.com/thesofproject/linux/issues/2748) 才能为扬声器供电。
> 
> ALCPlugFix-Swift 尚不支持 Short Hand Syntax Verb Command，需要等 [black-dragon74/ALCPlugFix-Swift#13](https://github.com/black-dragon74/ALCPlugFix-Swift/pull/13) 合并。

我使用你提交的ALCPlugFix-Swift#13 ，然后允许
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <array>
    <dict>
      <key>Comment</key>
      <string>0x20 0x500 0x24</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x24</string>
      <key>Verb</key>
      <string>0x500</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x400 0x41</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x41</string>
      <key>Verb</key>
      <string>0x400</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x500 0x26</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x26</string>
      <key>Verb</key>
      <string>0x500</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x400 0x2</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x2</string>
      <key>Verb</key>
      <string>0x400</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x400 0x0</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x0</string>
      <key>Verb</key>
      <string>0x400</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x400 0x0</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x0</string>
      <key>Verb</key>
      <string>0x400</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x4b0 0x20</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x20</string>
      <key>Verb</key>
      <string>0x4b0</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x500 0x24</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x24</string>
      <key>Verb</key>
      <string>0x500</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x400 0x42</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x42</string>
      <key>Verb</key>
      <string>0x400</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x500 0x26</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x26</string>
      <key>Verb</key>
      <string>0x500</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x400 0x2</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x2</string>
      <key>Verb</key>
      <string>0x400</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x400 0x0</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x0</string>
      <key>Verb</key>
      <string>0x400</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x400 0x0</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x0</string>
      <key>Verb</key>
      <string>0x400</string>
    </dict>
    <dict>
      <key>Comment</key>
      <string>0x20 0x4b0 0x20</string>
      <key>Enabled</key>
      <true />
      <key>Node ID</key>
      <string>0x20</string>
      <key>On Boot</key>
      <true />
      <key>On Connect</key>
      <false />
      <key>On Disconnect</key>
      <true />
      <key>On Mute</key>
      <false />
      <key>On Sleep</key>
      <false />
      <key>On Unmute</key>
      <false />
      <key>On Wake</key>
      <true />
      <key>Param</key>
      <string>0x20</string>
      <key>Verb</key>
      <string>0x4b0</string>
    </dict>
  </array>
</plist>
```
还是没有声音，不知道还差哪一步？

**Comment by Sulisong** [comment]
这个是根据linux精简转的，一样无效，不知道哪里问题
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>Comment</key>
		<string>0x20 0x500 0x26</string>
		<key>Enabled</key>
		<true/>
		<key>Node ID</key>
		<string>0x20</string>
		<key>On Boot</key>
		<false/>
		<key>On Connect</key>
		<true/>
		<key>On Disconnect</key>
		<false/>
		<key>On Mute</key>
		<false/>
		<key>On Sleep</key>
		<false/>
		<key>On Unmute</key>
		<false/>
		<key>On Wake</key>
		<false/>
		<key>Param</key>
		<string>0x26</string>
		<key>Verb</key>
		<string>SET_COEF_INDEX</string>
	</dict>
	<dict>
		<key>Comment</key>
		<string>0x20 0x400 0x2</string>
		<key>Enabled</key>
		<true/>
		<key>Node ID</key>
		<string>0x20</string>
		<key>On Boot</key>
		<false/>
		<key>On Connect</key>
		<true/>
		<key>On Disconnect</key>
		<false/>
		<key>On Mute</key>
		<false/>
		<key>On Sleep</key>
		<false/>
		<key>On Unmute</key>
		<false/>
		<key>On Wake</key>
		<false/>
		<key>Param</key>
		<string>0x0002</string>
		<key>Verb</key>
		<string>SET_PROC_COEF</string>
	</dict>
	<dict>
		<key>Comment</key>
		<string>0x20 0x400 0x0</string>
		<key>Enabled</key>
		<true/>
		<key>Node ID</key>
		<string>0x20</string>
		<key>On Boot</key>
		<false/>
		<key>On Connect</key>
		<true/>
		<key>On Disconnect</key>
		<false/>
		<key>On Mute</key>
		<false/>
		<key>On Sleep</key>
		<false/>
		<key>On Unmute</key>
		<false/>
		<key>On Wake</key>
		<false/>
		<key>Param</key>
		<string>0x0000</string>
		<key>Verb</key>
		<string>SET_PROC_COEF</string>
	</dict>
	<dict>
		<key>Comment</key>
		<string>0x20 0x400 0x0</string>
		<key>Enabled</key>
		<true/>
		<key>Node ID</key>
		<string>0x20</string>
		<key>On Boot</key>
		<false/>
		<key>On Connect</key>
		<true/>
		<key>On Disconnect</key>
		<false/>
		<key>On Mute</key>
		<false/>
		<key>On Sleep</key>
		<false/>
		<key>On Unmute</key>
		<false/>
		<key>On Wake</key>
		<false/>
		<key>Param</key>
		<string>0x0000</string>
		<key>Verb</key>
		<string>SET_PROC_COEF</string>
	</dict>
	<dict>
		<key>Comment</key>
		<string>0x20 0x4b0 0x20</string>
		<key>Enabled</key>
		<true/>
		<key>Node ID</key>
		<string>0x20</string>
		<key>On Boot</key>
		<false/>
		<key>On Connect</key>
		<true/>
		<key>On Disconnect</key>
		<false/>
		<key>On Mute</key>
		<false/>
		<key>On Sleep</key>
		<false/>
		<key>On Unmute</key>
		<false/>
		<key>On Wake</key>
		<false/>
		<key>Param</key>
		<string>0xb020</string>
		<key>Verb</key>
		<string>SET_PROC_COEF</string>
	</dict>
</array>
</plist>
```

**Comment by Sulisong** [comment]
alc-verb 发送了也无效，哎，搞不懂大佬是怎么搞定的
```
alc-verb  0x20 SET_COEF_INDEX 0x24
alc-verb  0x20 SET_PROC_COEF 0x0041
alc-verb  0x20 SET_COEF_INDEX 0x26
alc-verb  0x20 SET_PROC_COEF 0x0002
alc-verb  0x20 SET_PROC_COEF 0x0000
alc-verb  0x20 SET_PROC_COEF 0x0000
alc-verb  0x20 SET_PROC_COEF 0xb020
alc-verb  0x20 SET_COEF_INDEX 0x24
alc-verb  0x20 SET_PROC_COEF 0x0042
alc-verb  0x20 SET_COEF_INDEX 0x26
alc-verb  0x20 SET_PROC_COEF 0x0002
alc-verb  0x20 SET_PROC_COEF 0x0000
alc-verb  0x20 SET_PROC_COEF 0x0000
alc-verb  0x20 SET_PROC_COEF 0xb020
```
![image](https://user-images.githubusercontent.com/40148554/140647758-21107833-7a49-4f0f-8ba7-946ee1981aa9.png)

**Comment by SukkaW** [comment]
> alc-verb 发送了也无效，哎，搞不懂大佬是怎么搞定的
> 
> ```
> alc-verb  0x20 SET_COEF_INDEX 0x24
> alc-verb  0x20 SET_PROC_COEF 0x0041
> alc-verb  0x20 SET_COEF_INDEX 0x26
> alc-verb  0x20 SET_PROC_COEF 0x0002
> alc-verb  0x20 SET_PROC_COEF 0x0000
> alc-verb  0x20 SET_PROC_COEF 0x0000
> alc-verb  0x20 SET_PROC_COEF 0xb020
> alc-verb  0x20 SET_COEF_INDEX 0x24
> alc-verb  0x20 SET_PROC_COEF 0x0042
> alc-verb  0x20 SET_COEF_INDEX 0x26
> alc-verb  0x20 SET_PROC_COEF 0x0002
> alc-verb  0x20 SET_PROC_COEF 0x0000
> alc-verb  0x20 SET_PROC_COEF 0x0000
> alc-verb  0x20 SET_PROC_COEF 0xb020
> ```
> 
> ![image](https://user-images.githubusercontent.com/40148554/140647758-21107833-7a49-4f0f-8ba7-946ee1981aa9.png)

```bash
#!/usr/bin/bash
# Left speaker
./alc-verb  0x20 0x500 0x24
./alc-verb  0x20 0x400 0x41
./alc-verb  0x20 0x500 0x26
./alc-verb  0x20 0x400 0x2
./alc-verb  0x20 0x400 0x0
./alc-verb  0x20 0x400 0x0
./alc-verb  0x20 0x4b0 0x20

# Right speaker
./alc-verb  0x20 0x500 0x24
./alc-verb  0x20 0x400 0x42
./alc-verb  0x20 0x500 0x26
./alc-verb  0x20 0x400 0x2
./alc-verb  0x20 0x400 0x0
./alc-verb  0x20 0x400 0x0
./alc-verb  0x20 0x4b0 0x20
```

**Comment by Sulisong** [comment]
https://gitee.com/YasuStudio/fix-speaker-y9000x

大佬你看这个，写了一键脚步，可以使用

**Comment by XQLsj99** [comment]
> https://gitee.com/YasuStudio/fix-spe

> https://gitee.com/YasuStudio/fix-speaker-y9000x
> 
> 大佬你看这个，写了一键脚步，可以使用

12.01已经用上！非常感谢各位大佬！不过目前3.5mm有线耳机与扬声器无法切换，算是一个小瑕疵，但是不管怎样，哑巴终于出声了，牛b！

**Comment by Sulisong** [comment]
> > https://gitee.com/YasuStudio/fix-spe
> 
> > https://gitee.com/YasuStudio/fix-speaker-y9000x
> > 大佬你看这个，写了一键脚步，可以使用
> 
> 12.01已经用上！非常感谢各位大佬！不过目前3.5mm有线耳机与扬声器无法切换，算是一个小瑕疵，但是不管怎样，哑巴终于出声了，牛b！

我这里耳机可以正常切换的，y9000x 2020版本

**Comment by l1467016812** [comment]
> > > https://gitee.com/YasuStudio/fix-spe
> > 
> > 
> > > https://gitee.com/YasuStudio/fix-speaker-y9000x
> > > 大佬你看这个，写了一键脚步，可以使用
> > 
> > 
> > 12.01已经用上！非常感谢各位大佬！不过目前3.5mm有线耳机与扬声器无法切换，算是一个小瑕疵，但是不管怎样，哑巴终于出声了，牛b！
> 
> 我这里耳机可以正常切换的，y9000x 2020版本

感谢大佬们的努力，3.5mm耳机插入时，无法切换内置扬声器，输出设备仅有一个3.5mm耳机。蓝牙耳机、USB耳机与3.5mm耳机同时插入，有多个输出设备可以切换，但依旧无内置扬声器选项。拔除3.5mm耳机后，出现内置扬声器选项。

**Comment by Sulisong** [comment]
> > > > https://gitee.com/YasuStudio/fix-spe
> > > 
> > > 
> > > > https://gitee.com/YasuStudio/fix-speaker-y9000x
> > > > 大佬你看这个，写了一键脚步，可以使用
> > > 
> > > 
> > > 12.01已经用上！非常感谢各位大佬！不过目前3.5mm有线耳机与扬声器无法切换，算是一个小瑕疵，但是不管怎样，哑巴终于出声了，牛b！
> > 
> > 
> > 我这里耳机可以正常切换的，y9000x 2020版本
> 
> 感谢大佬们的努力，3.5mm耳机插入时，无法切换内置扬声器，输出设备仅有一个3.5mm耳机。蓝牙耳机、USB耳机与3.5mm耳机同时插入，有多个输出设备可以切换，但依旧无内置扬声器选项。拔除3.5mm耳机后，出现内置扬声器选项。

哦哦，我理解你的意思了。好像系统默认就是这样运行的，有线输出就隐藏扬声器，我相信白果也是这样。蓝牙或者type-c就可以切换。

**Comment by SukkaW** [comment]
> 感谢大佬们的努力，3.5mm耳机插入时，无法切换内置扬声器，输出设备仅有一个3.5mm耳机。蓝牙耳机、USB耳机与3.5mm耳机同时插入，有多个输出设备可以切换，但依旧无内置扬声器选项。拔除3.5mm耳机后，出现内置扬声器选项。

这个是 ALC285 声卡的 Quirk，不支持多输出热切换；和在 Linux 下的表现是一致的。

**Comment by XIAO-FJ** [comment]
> 
> 这个是 ALC285 声卡的 Quirk，不支持多输出热切换；和在 Linux 下的表现是一致的。

好的，明白了，接入耳机时，麦克风也不会同样切换成耳机麦克风，应该也是同样的问题。

**Comment by M69W** [comment]
隔壁小新pro13 关注一波，小新pro13 的麦克风还有希望不

**Comment by XIAO-FJ** [comment]
各位大佬，经过使用，好像电脑睡眠、重启或者中断播放一会儿，会出现无声现象，需要再次启用才有声音，也发现插拔3.5mm耳机也可再次激活扬声器，不知道怎么回事，不知道你们有没有这现象？

**Comment by ImKujio** [comment]
> 各位大佬，经过使用，好像电脑睡眠、重启或者中断播放一会儿，会出现无声现象，需要再次启用才有声音，也发现插拔3.5mm耳机也可再次激活扬声器，不知道怎么回事，不知道你们有没有这现象？

我的也是+1

**Comment by M69W** [comment]
小新pro13 在电池模式下，耳机偶尔会出现无声状态，
临时解决：[在设置，声音。打开这个界面并不要关闭能解决类似的问题.](https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/63#issuecomment-914766983)

**Comment by SukkaW** [comment]
> 各位大佬，经过使用，好像电脑睡眠、重启或者中断播放一会儿，会出现无声现象，需要再次启用才有声音，也发现插拔3.5mm耳机也可再次激活扬声器，不知道怎么回事，不知道你们有没有这现象？

> > 各位大佬，经过使用，好像电脑睡眠、重启或者中断播放一会儿，会出现无声现象，需要再次启用才有声音，也发现插拔3.5mm耳机也可再次激活扬声器，不知道怎么回事，不知道你们有没有这现象？
> 
> 我的也是+1

可能睡眠唤醒时，ALCPlugFix 没能 Hook 到 Wake 事件。

**Comment by ImKujio** [comment]
> > 各位大佬，经过使用，好像电脑睡眠、重启或者中断播放一会儿，会出现无声现象，需要再次启用才有声音，也发现插拔3.5mm耳机也可再次激活扬声器，不知道怎么回事，不知道你们有没有这现象？
> 
> > > 各位大佬，经过使用，好像电脑睡眠、重启或者中断播放一会儿，会出现无声现象，需要再次启用才有声音，也发现插拔3.5mm耳机也可再次激活扬声器，不知道怎么回事，不知道你们有没有这现象？
> > 
> > 
> > 我的也是+1
> 
> 可能睡眠唤醒时，ALCPlugFix 没能 Hook 到 Wake 事件。

确实只在电池模式下会出现,但不止是睡眠,只要停止声音播放10s就会出现扬声器无声的情况

**Comment by XIAO-FJ** [comment]
> > > 各位大佬，经过使用，好像电脑睡眠、重启或者中断播放一会儿，会出现无声现象，需要再次启用才有声音，也发现插拔3.5mm耳机也可再次激活扬声器，不知道怎么回事，不知道你们有没有这现象？
> > 
> > 
> > > > 各位大佬，经过使用，好像电脑睡眠、重启或者中断播放一会儿，会出现无声现象，需要再次启用才有声音，也发现插拔3.5mm耳机也可再次激活扬声器，不知道怎么回事，不知道你们有没有这现象？
> > > 
> > > 
> > > 我的也是+1
> > 
> > 
> > 可能睡眠唤醒时，ALCPlugFix 没能 Hook 到 Wake 事件。
> 
> 确实只在电池模式下会出现,但不止是睡眠,只要停止声音播放10s就会出现扬声器无声的情况

Linux下好像也会出现这个问题，联想社区https://club.lenovo.com.cn/thread-7817162-1-1.html

**Comment by M69W** [comment]
> 小新pro13 在电池模式下，耳机偶尔会出现无声状态， 临时解决：[在设置，声音。打开这个界面并不要关闭能解决类似的问题.](https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/63#issuecomment-914766983)

小新pro13 也类似，
`电源模式下，耳机正常使用，并没出现无声现象。`

**Comment by SukkaW** [comment]
@XIAO-FJ @M69W @ImKujio 经过确认，可能和 macOS 的 coreaudiod 的 Bug 有关。重启 coreaudiod 守护进程可以解决：

```bash
sudo pkill coreaudiod && sudo launchctl start com.apple.audio.coreaudiod
```

**Comment by ImKujio** [comment]
> ```shell
> sudo pkill coreaudiod && sudo launchctl start com.apple.audio.coreaudiod
> ```

没有用啊，电池状态下马上就没声了，，，得插一下耳机再拔出来就又有声了

**Comment by ImKujio** [comment]
@SukkaW @XIAO-FJ 电池模式下一会就没声的问题我找到一个临时的解决方法，原理是关掉自动切换，改成每20秒发送一次。
原因是我发现没声时直接执行以下命令就又有声了：
![image](https://user-images.githubusercontent.com/18486297/144262888-cb0d0807-938f-4962-b322-98bde6db8a40.png)
所以直接写了个启动脚本从[开机/唤醒]开始每20秒就执行一次，
![image](https://user-images.githubusercontent.com/18486297/144263449-1e2b7a56-f401-4073-8348-568baa13e74d.png)
这样扬声器永远都没问题了，
测试了下插耳机没问题，拔掉耳机扬声器声音会在**0~20秒**后恢复正常。
如果有其他更优雅的解决办法麻烦告诉我！

**Comment by SukkaW** [comment]
https://github.com/acidanthera/AppleALC/pull/755

@M69W @XIAO-FJ @ImKujio @Sulisong

**Comment by ryan7n** [comment]
艾玛，看哭了。等了2年多，官方屁都没一个，还是社区给力，感恩各位大佬

**Comment by Sulisong** [comment]
> [acidanthera/AppleALC#755](https://github.com/acidanthera/AppleALC/pull/755)
> 
> @M69W @XIAO-FJ @ImKujio @Sulisong

nice，测试了可以静音了，现在就剩下电源休眠失效了。

**Comment by Sulisong** [comment]
@SukkaW 
![image](https://user-images.githubusercontent.com/40148554/149801080-7b068022-5810-415c-853a-9c17964a117b.png)
大佬看一下这个，休眠唤醒ALCPlugFix运行日志，最后一行是不是导致没有声音的原因。日志翻译：已保存启用噪声消除设置与默认设置相同 (=1)

**Comment by SukkaW** [comment]
> @SukkaW 大佬看一下这个，休眠唤醒ALCPlugFix运行日志，最后一行是不是导致没有声音的原因。日志翻译：已保存启用噪声消除设置与默认设置相同 (=1)

你的 Log 大概是 corrupt 了。我查了一下这条 message，在 ALCPlugFix 源码里没有，在 AppleALC 里也没有。关于这条报错唯一的资料是关于 OpenCV 的： https://stackoverflow.com/questions/53253563/opencv-c-xcode-on-mac-mojave-error-nscamerausagedescription

**Comment by playersun** [comment]
大佬们，请问下
我这边有时候重启有声音，有时候重启很多次都没有声音，请问是没加载到驱动吗？

**Comment by ryan7n** [comment]
linux内核已经修复了，mac应该也可以也可以移植一下

**Comment by superjinge** [comment]
> 

不要用重启, 关机-启动

**Comment by superjinge** [comment]
不要用重启,  关机+开机就行

**Comment by SukkaW** [comment]
> linux内核已经修复了，mac应该也可以也可以移植一下

去找 @black-dragon74 让他合并 https://github.com/black-dragon74/ALCPlugFix-Swift/pull/13

**Comment by ryan7n** [comment]
> > linux内核已经修复了，mac应该也可以也可以移植一下
> 
> 去找 @black-dragon74 让他合并 [black-dragon74/ALCPlugFix-Swift#13](https://github.com/black-dragon74/ALCPlugFix-Swift/pull/13) ，催我没有用。
> 
> 我已经把能做的都做了。AppleALC 我也定制了，用到的 alc command 我也总结出来了。上游工具链不修我这边没法做任何事情。
> 
> 再催我就把这条 issue 锁掉关了。再开 issue 问我 我就直接把仓库的 issue 也禁用掉。

对大佬的付出，有且只有感激，官方的无为更让人感觉到社区的温暖，没有催大佬的意思，我现在用ubuntu升级最新内核是正常的，所以就提了一嘴，希望能对大家有帮助

**Comment by xyz8899** [comment]
bash -c "$(curl -fsSL https://gitee.com/YasuStudio/fix-speaker-y9000x/raw/master/FixSpeaker-Y9000X.sh)"
不知道这个安装脚本有用没有，可以试试

**Comment by SukkaW** [comment]
- AppleALC 已经支持 Y9000X 声音布局。
- ALCPlugFix-Swift 已经兼容 Y9000X 扬声器功率放大器供电指令。
- 仓库内已经内置安装脚本：

https://github.com/SukkaW/Lenovo-Y9000X-Hackintosh#how-to-fix-y9000xs-speaker--%E5%A6%82%E4%BD%95%E4%BF%AE%E5%A4%8D-y9000x-%E7%9A%84%E6%89%AC%E5%A3%B0%E5%99%A8

**Comment by tangzhang1475** [comment]
貌似在14.5这个脚本已经失效，需要大佬们进一步研究适配。

**Comment by tangzhang1475** [comment]
貌似在14.5这个脚本已经失效，需要大佬们进一步研究适配。

**Comment by SukkaW** [comment]
> 貌似在14.5这个脚本已经失效，需要大佬们进一步研究适配。

扬声器供电放大器硬件接受指令即可上电，这个指令由扬声器硬件型号决定、升级系统是不会变的。
我猜测 macOS 14 改变了系统服务的执行方式或者类型，导致 ALCPlugFix-Swift 的系统服务没有在后台定期执行上电指令。

**Comment by tangzhang1475** [comment]
麻烦大大查明原因，帮忙解决，万分感谢！
