### ISSUE TITLE
Possible to build for Yoga S740 - 15IRH too? 

### ISSUE THREAD

**Issue by AlkoKod** [SukkaW/Lenovo-Y9000X-Hackintosh#8]
Hello, I have a laptop Lenovo Yoga s740 15 irh with: 

SSD: Samsung PM981 (will be changed with kingston)
CPU: HexaCore Intel Core i7-9750H, 2300 MHz (23 x 100)
Wifi: Intel Wireless AC 9560 160MHz
USB: 3.1
GC: GTX 1650 MaxQ

Is this the same device? Thanks in advance.

**Comment by SukkaW** [comment]
No.

`Y9000X 2020` is `Legion S740-15IRH` which has no Dedicated Graphics card.
